### ISSUE TITLE
Relocate some of the Cryo-EM's menu options

### ISSUE THREAD

**Issue by hgonomeg** [hgonomeg/coot#10]
Relocate the following after #5 is done:

`coot_gui.py` >> `add_module_cryo_em_gui()`:
![image](https://user-images.githubusercontent.com/48153724/191957328-59deab1b-bf90-4c8b-93bb-cc79e69c0244.png)

# Tasks
* [ ] Relocate what belongs in `Modelling`
* [ ] It would be nice to make those items actually work / port them to gtk4; now they cause exceptions to be thrown
* [ ] Do something with items that belong in `Preferences` (I don't know when the prefs dialog will get reimplemented)

**Comment by hgonomeg** [comment]
I think this issue has already been tackled at some point.
