### ISSUE TITLE
Fix up the Fetch dialogs

### ISSUE THREAD

**Issue by hgonomeg** [hgonomeg/coot#19]
Fetch dialogs are getting converted into overlay frames.

# General observations

Initialization is messed up.

## Unify initialization of properties that remain constant

What is an overlay should be moved inside `Gtk.Overlay` in XML, as a `child` of type `overlay`.

## Extract single-shot startup initialization code for each "Fetch *" frame

The actions that show up components like the fetch frames should only do one thing - display them.
...possibly minor other things as well, e.g. managing focus.
In either case, no initialization should happen in them.

All widget shuffling, aligning, event controllers and other initialization code is meant to land in a new file named along the lines of `setup-gui-components.cc`, exporting a unction like `setup_gui_components()` to be called once during startup, possibly after the call to `create_actions()`.

# Convention

* Add "Cancel" buttons
* Esc key should act the same as "Cancel" button, ~preferably utilizing the same routine (e.g. by explicitly emitting 'clicked' signal on the button)~ which is: calling `gtk_widget_hide` on the target frame.

# Tasks

Fix the following Fetch * / add them to overlay:

* [x] PDB using Accession Code
  * [x] Convert into overlay
  * [x] Unify initialization
  * [x] Add Cancel button + Esc handler
* [x] PDB & MAP using EDS
  * [x] Convert into overlay
  * [x] Unify initialization
  * [x] Add Cancel button + Esc handler
* [x] PDB & MAP using PDB-REDO 
  * [x] Convert into overlay
  * [x] Unify initialization
  * [x] Add Cancel button + Esc handler
* ~~Corresponding AlphaModel & Superpose~~
  * ~~Convert into overlay~~
  * ~~Unify initialization~~
  * ~~Add Cancel button + Esc handler~~
* [x] AlphaFold Model via Uniprot ID
  * [x] Convert into overlay
  * [x] Unify initialization
  * [x] Add Cancel button + Esc handler
* ~~PDBe Ligand Description~~
  * ~~Convert into overlay~~
  * ~~Unify initialization~~
  * ~~Add Cancel button + Esc handler~~

Side tasks:

* [x] Get Monomer
  * [x] Unify initialization
  * [x] Add Esc handler

**Comment by hgonomeg** [comment]
* [ ] e

**Comment by hgonomeg** [comment]
Done. Closing.
