### ISSUE TITLE
Improve margins and spacings of Cryo-EM's dialogs

### ISSUE THREAD

**Issue by hgonomeg** [hgonomeg/coot#3]
Calculate -> Modules -> Cryo-EM.

That makes a menu button, the subsequent dialogs from the menu items are a mess.
Fix the margins and spacings.
The widgets in them need to be spaced out. 

Have a look at the GNOME HIG for guidance.

Is this at ~~`extensions.py`~~ `coot_gui.py` .

# Tasks

* [x] Inspect
* [x] Improve 'Sharpen / Bloor' Dialog
* [x] Improve 'Multi-sharpen / Use Refmac for Sharpening' Dialog
* [x] Improve 'Flip Map Hand / Molecule Chooser' Dialog
* [x] Make sure all is good

**Comment by KartoniarzEssa** [comment]
Powodzenia pozdrawiam z rodzinką![RDT_20220919_1341297217803596456312480.jpg](https://user-images.githubusercontent.com/81422890/191255657-9828124f-df41-49e2-9a97-b433c7175771.jpg)

**Comment by JakubCygaro** [comment]
Goodbye and thanks for the fish
![image345](https://user-images.githubusercontent.com/57292664/191256118-23971455-9010-45dd-ac5f-7bde2614166c.jpg)

**Comment by hgonomeg** [comment]
Merged: #7
