### ISSUE TITLE
Create new ligand editor

### ISSUE THREAD

**Issue by hgonomeg** [hgonomeg/coot#39]
Ligand Editor is the other major component which requires a rewrite from scratch after the removal of `GooCanvas`.

As I'm writing this, I've already gotten to the point where the new implementation is somewhat usable.
Things still to be done can be found on the list below.

# Something to consider

* A system of keyboard selections and navigation to improve ergonomics, like in ChemDraw.
* Functional group insertion

# Tasks

* [x] Allow nonsensical molecules (preferably with a toggle)
* [x] Convert tools to toggle buttons or display an indication of what tool is being used
* [x] Diagnoze and fix the benzene issue
* [x] Diagnoze and fix invalid "centered" double bonds e.g. here `C[C@H](NC(=O)[C@H](C)NC(=O)[C@@H](N)CCP(C)(=O)O)C(=O)O`
* [x] Enter-handlers in entry-dialogs
* [x] Make sure that explicit hydrogens aren't broken (and fix them if so)
* [x] Add documentation tooltips
* [x] Confirmation dialog when there are unsaved changes and the user wants to quit or `File->New`
* ~~Dialogs into overlays~~ Not sure if it's a good idea
* [x] Initial Coot integration
  * [x] Prepare icons and `.ui` (and remaining env stuff) for distribution
    * [x] icons
    * [x] `layla.ui`
    * ~~Linkage of Python setup~~ **deferred**
  * [x] Passing filenames resulting from the "Apply" dialog to Coot
    * [x] Create custom GObject with a custom signal ("cif-file-generated" or something like that)
    * [x] Emit the signal from from within Layla
    * [x] Handle the signal in Coot
  * [x] Somehow accepting molecules as input from Coot
     * [x] mmdb → RDKit conversion
     * [x] Append molecule
  * [x] Instantiating and de-instantiating Layla
* [x] Fix invalid rendering of the final arc in wavy bonds (which happens for certain angles sometimes)
* [x] Implement removing whole molecules from the editor
  * [x] Ctrl+click ?
  * [x] When the last atom gets removed
* [x] ~~SMILES button~~ _Not needed in Layla_
* [x] Fetch
* [x] "Env. Residues" does what exactly? _**- displays FLEV**_
* [x] How should "remove hydrogens" work? Is it still needed? _**- Yes. It should remove explicit non-polar hydrogens**_
* [x] "Apply" button
  * [x] Get to know more about how "Apply" is expected to work
  * [x] Implement dialogs
  * [x] Implement launching `acedrg` generator
  * [x] Implement launching `Grade2` generator
  * [x] Integrate with Coot
* [x] File->New 
* [x] Keybindings
* [x] Port the UI to XML
  * [x] Recreate the UI in XML
  * [x] Setup signal handlers
  * [x] Setup actions
* [x] Icons
* [x] Rendering of exports
  * [x] Design common rendering API
  * [x] Port widget-rendering code to use the common rendering API
  * [x] Produce PDFs (use `cairo` PDF surface?)
  * [x] Produce SVGs (special backend? Or can `cairo` SVG surface do it?)
  * [x] Render PNGs (`cairo`  like in the widget?)
* [x] Bond insertion tool: Support for click and drag (to create rings and bonds between existent atoms)
* [x] Atom insert tool should 
  * [x] _should it do anything for bonds? Insert an atom in between?_
  * [x] Handle the 'X'/other element mode
* [x] Refactor tools to use a common, more streamlined interface
  * [x] Refactor `MoveTool` and`RotateTool` into a single special tool (`TransformManager`), present independently of other tools (`MoveTool` and `RotateTool` are to become interfaces to the `TransformManager`)
  * [x] Identify common aspects of tools and design adequate classes that reflect this abstraction
  * [x] Do the refactor (get rid of the gazillion tool-specific `do_something(x,y)` functions from `ActiveTool`)
* [x] Display SMILES
* [x] About dialog
* [x] Set colors for F, Br, etc.
* [x] Add a limit to the history length to prevent continuous increase of memory usage
* [x] Implement charge tool
  * [x] Bare-bones usability
  * [x] ~~Sensible computation of plausible ions~~ Left-click to decrease charge, right click to increase it
* [x] Canvas management
  * ~~Proper widget sizing~~ **another issue**
  * [x] Correct molecule separation when changing scale
* [x] Drawing functionality
  * [x] Rework "appendix": draw _"NH2+"_
  * [x] Correct appendix orientation for different angles
  * [x] Rework appendix/symbol alignment and rendering
    * [x] Adjust x-alignment when inside rings
    * [x] Align the rendered text so as to make the bonds always point to the symbol of the "main" atom
    * [x] Get rid of the background or improve its' sizing
  * [x] Improve double bonds
    * [x] Shorten double bonds accordingly to the angle between bonds
    * [x] Add support for "centered" double bonds
  * [x] Bond Geometry
    * [x] Wedges
    * [x] Dashes
    * [x] Wavy bonds
  * [x] Different display options?
    * [x] Atom indices
    * [x] Atom names
* [x] Geometric transforms
  * [x] Rotating by angle
  * [x] Flipping by axes
* [x] Implement geometry tool
* [x] Monomer library imports

# Deferred to be taken care of later

* FLEV - #61 
* Show alerts - #60 
* Drawing bond geometry: wedges inside rings - #59 
* Drawing bond geometry: darted wedges - #59 
* QED ? - #62 
* Linkage of Python setup - #63 
* Rework canvas sizing -#66

**Comment by hgonomeg** [comment]
Some cool molecules for testing

| Substance                        | SMILES code                                                                                   |
|----------------------------------|-----------------------------------------------------------------------------------------------|
| Lorazepam                        | C1=CC=C(C(=C1)C2=NC(C(=O)NC3=C2C=C(C=C3)Cl)O)Cl                                               |
| Diazepam                         | CN1C2=C(C=C(Cl)C=C2)C(C3=CC=CC=C3)=NCC1=O                                                     |
| Nicotine                         | CN1CCCC1C2=CN=CC=C2                                                                           |
| Caffeine                         | C[n]1cnc2N(C)C(=O)N(C)C(=O)c12                                                                |
| Guanidinium ion                  | C(=[NH2+])(N)N                                                                                |
| Pregabalin                       | CC(C)CC(CC(=O)O)CN                                                                            |
| Modafinil                        | C1=CC=C(C=C1)C(C2=CC=CC=C2)S(=O)CC(=O)N                                                       |
| Ascorbic acid                    | OC=1C(OC(=O)C=1O)\[C\@\@H\](O)CO                                                                |
| Fluoxetine                       | CNCCC(c1ccccc1)Oc2ccc(cc2)C(F)(F)F                                                            |
| Bupropion                        | O=C(C(C)NC(C)(C)C)C1=CC=CC(Cl)=C1                                                             |
| Phencyclidine                    | c1ccccc1C2(CCCCC2)N3CCCCC3                                                                    |
| Haloperidol                      | c1cc(ccc1C(=O)CCCN2CCC(CC2)(c3ccc(cc3)Cl)O)F                                                  |
| Aflatoxin B1                     | O=C5C=4C(=O)Oc3c1c(OC2O\C=C/C12)cc(OC)c3C=4CC5                                                |
| Sarin                            | FP(=O)(OC(C)C)C                                                                               |
| Mitrazapine                      | n1cccc3c1N4C(c2ccccc2C3)CN(C)CC4                                                              |
| VX                               | O=P(OCC)(SCCN(C(C)C)C(C)C)C                                                                   |
| LSD                              | CCN(CC)C(=O)[C@H]1CN([C@@H]2Cc3c[nH]c4c3c(ccc4)C2=C1)C                                        |
| Pyridoxal phosphate (vitamin B6) | O=Cc1c(O)c(C)ncc1COP(O)(O)=O                                                                  |
| Dinitrobisphenol A               | CC(C)(C1=CC(=C(C=C1)O)\[N+\](=O)[O-])C2=CC(=C(C=C2)O)\[N+\](=O)[O-]                           |
| L-Dopa                           | O=C(O)\[C@@H\](N)Cc1cc(O)c(O)cc1                                                              |
| Gabapentin                       | O=C(O)CC1(CN)CCCCC1                                                                           |
| Vitamin D3                       | O[C@@H]1CC(\C(=C)CC1)=C\C=C2/CCC[C@]3([C@H]2CC[C@@H]3\[C@H\](C)CCCC(C)C)C                     |
| Aspirin                          | O=C(C)Oc1ccccc1C(=O)O                                                                         |
| Acetylocholine                   | CC(=O)OCC\[N+\](C)(C)C                                                                          |
| Paracetamol                      | CC(=O)Nc1ccc(O)cc1                                                                            |
| Psylocibin                       | CN(C)CCC1=CNC2=C1C(=CC=C2)OP(=O)(O)O                                                          |
| Buprenorphine                    | Oc7ccc5c1c7O\[C@H\]3\[C@\]6(OC)\[C@H\](C\[C@@\]2(\[C@H\](N(CC\[C@@\]123)CC4CC4)C5)CC6)\[C@@\](O)(C)C(C)(C)C |
| Methyl orange                    | [Na+].CN(C)c2ccc(/N=N/c1ccc(cc1)S([O-])(=O)=O)cc2                                             |
| Phenolophthalein                 | O=C1OC(C2=C1C=CC=C2)(C3=CC=C(C=C3)O\[H\])C4=CC=C(C=C4)O\[H\]                                      |
| Bromothymol Blue                 | Brc1c(O)c(cc(c1C)C3(OS(=O)(=O)c2ccccc23)c4cc(c(O)c(Br)c4C)C(C)C)C(C)C                         |
| ATP                              | O=P(O)(O)OP(=O)(O)OP(=O)(O)OC\[C@H\]3O\[C@@H\](n2cnc1c(ncnc12)N)\[C@H\](O)\[C@@H\]3O                  |
| Amoxillicin                      | O=C(O)\[C@@H\]2N3C(=O)\[C@@H\](NC(=O)\[C@@H\](c1ccc(O)cc1)N)\[C@H\]3SC2(C)C                           |
|                                  |                                                                                               |
|                                  |                                                                                               |

**Comment by hgonomeg** [comment]
I'll soon merge the working branch into `main` to enable making progress on the build system integration. The remaining work shall continue on the working branch.

**Comment by hgonomeg** [comment]
This can all soon be merged
