### ISSUE TITLE
Cleanup after merging validation graphs

### ISSUE THREAD

**Issue by hgonomeg** [hgonomeg/coot#40]
Validation graphs have been plugged into the codebase (by Paul) and thus #33 can be considered closed.
There are many things however that require attention.

## Important architectural notes

`geometry_dialog` widget used to be where the old GooCanvas validation graphs had been stored.
Having `geometry_dialog` as this multi-purpose container led to a somewhat convoluted mixture of validation graph related code and code which has nothing to do with validation graphs. 
`geometry_dialog` needs a refactor (at least a wipe of validation graph related things).

## Something to look into

> I do prefer however, in `on_validation_graph_checkbutton_toggled()` that he molecule index is determinded from the model combobox
> having `graphic_info_t` variables to store the values of molecule selections is a hang-over from the GtkOptionmenu days. 

# Tasks

* [x] Find and remove the old enum for representing graph types. It might get confused with the new enum which would be really bad.
* [x] Remove `dynamic-menus.{cc,hh}`
* [x] De-duplicate `src/validation-graph-widget.{cc,h}}`, `src/validation-graphs.{cc,hh}` vs `src/validation-graphs/`
* [x] Delete the old class from  `src/validation-graphs/validation-graphs.hh`
* [ ] Inspect what's going on with `EMSCRIPTEN` and `*_min_max_t`
* [ ] Inspect unresolved todos at `graphics-info-graphs.cc`
* [ ] Remove old code from `graphics-info-graphs.cc`
* [ ] Cleanup / refactor `geometry_dialog`:
  * [ ]  `graphics-info.h` likely stores a lot of old unused code (look at `// ------------- validation: -------------------`)
  * [ ] Separate-out useful stuff and delete `geometry-graphs.{cc,hh}`
* [ ] Remove the old dialog used for validation graphs (it likely has been left behind)
  * [x] Some traces of the dialog have been removed already
* [ ] Make sure that `update_validation_graphs()` looks good

**Comment by hgonomeg** [comment]
![image](https://github.com/hgonomeg/coot/assets/48153724/0d85d4fd-7d92-44dc-9a52-6ba08d24e4ce)

I'm merging #47 at this point to prevent excessive merge conflicts in the future.
New pull request (and branch) will be created to address the tasks remaining in the list.
