### ISSUE TITLE
Enable loading more Python modules

### ISSUE THREAD

**Issue by hgonomeg** [hgonomeg/coot#5]
The "Cryo-EM" module is one of a number of modules.

The other modules will need to be added in the same way, like it's done on the `gtk3` branch.

Some reference code: https://github.com/pemsley/coot/commit/0d77807254aa28ed26b860f3764bc8f1321eb881

# Tasks

* [x] Make a list of modules to be re-enabled for `gtk4`
* [x] Create a helper function for GSimpleActions
* ~~Finish porting Cryo-EM to gtk4~~ See #10 
* [x] Re-enable modules and improve the looks of their dialogs
  * [x] CCP4
  * [x] Carbohydrate
  * [x] ProSMART
  * [x] Refine
  * [x] Restraints
  * ~~SHELX~~
  * ~~RCrane~~

**Comment by hgonomeg** [comment]
For Carbohydrate / Glyco: see `python/populate_python_menus.py:186`

**Comment by hgonomeg** [comment]
Merged
