### ISSUE TITLE
Fix-up the Export dialogs

### ISSUE THREAD

**Issue by hgonomeg** [hgonomeg/coot#50]
> The "Export Map" and "Export Map Fragment" dialogs are a mess. They should be overlays in the style of the "Get Monomer" overlay.
> 
> (The resulting file choosers should of course have their own dialog - like any open file or save file operation)

# Tasks

* [x] Convert the dialogs into overlays
* [x] Find out how they should work in the first place
* [x] Fix their usage
