### ISSUE TITLE
Lhasa: Port Layla for Emscripten

### ISSUE THREAD

**Issue by hgonomeg** [hgonomeg/coot#64]
# Description

The new ligand builder - _Layla_ - needs to have its' core exposed for Emscripten/WASM bindings, for usage in Moorhen.
This means that core widget data has to be abstracted away from `GtkWidget` context.

# Design

## Editor state class

_We need nothing more than the widget/canvas. Frontend takes care of the rest_

## Core and Tools API

_Everything stays as it is._

## Drawing (part of model API)

It's impractical to do webapp-side drawing with `cairo`. 
Drawing operations have to be abstracted away using a class that will yield a list of drawing operations, to be then executed in JS-side.
We will likely end up using D3.js for rendering (as SVGs).

## Testing / mock webapp

The development subproject to build and test Lhasa web interface is called `LhasaReact` and it belongs to Moorhen.
It will later be made production-ready.

# Tasks

* [x] Setup `lhrs` project as a good starter
* [x] Check-out Emscripten binding generators and test them on a trivial C++ class
* [x] Make Lhasa compile using Emscripten
  * [x] Provide dependencies
    * [x] RDKit
    * [x] libgraphene
  * [x] Abstract-away GTK/Glib-dependent things inside of `ligand_editor_canvas`
    * [x] `gtk_widget_queue_redraw`, `gtk_widget_queue_resize`
    * [x] Signals
    * [x] `g_warning`, `g_error`, `g_info`, `g_debug`, etc.
  * [x] ~~Decide what to do with `LaylaState` - should it be ported or should it be a part of the webapp (JS/Rust)~~ No need to port that. Should be a part of the webapp.
  * [x] Make the sources compile to produce a static wasm library (?) with JS bindings
  * [x] Abstract-away cairo drawing APIs inside of `model.cpp`
    * [x] Plain cairo calls
    * [x] Text measurement
    * [x] Text rendering & styling
* [x] Implement abstractions over `gtk_widget_queue_*`
  * [x] `gtk_widget_queue_draw` - some simple replacement
  * ~~`gtk_widget_queue_resize` - decide how it should work in the browser~~ - deferred to a separate issue
* [x] Implement the new abstracted-away drawing API for WASM
  * [x] Implement plain cairo calls + intermediate representation for JS/TS
    * ~~Path management~~ - Moved to a separate isssue
    * [x] Lines
    * ~~Arcs~~ - Moved to a separate issue
    * [x] Text
  * [x] Implement D3.js SVG generation
    * [x] Lines
    * ~~Paths~~ - Now a part of `LhasaReact`
    * ~~Arcs~~ - Now a part of `LhasaReact`
    * [x] Text
  * ~~Implement text measurement~~ - now a part of `LhasaReact`
  * [x] Implement text styling & rendering
* [x] Wire-up the mock webapp
  * [x] Add simple UI
  * [x] Display the canvas
  * [x] Wire-up buttons
  * [x] Wire-up menus (/ menu replacements)
    * [x] Rendering modes
    * [x] Edit undo/redo
    * [x] SMILES Imports
  * [x] Handle click events
  * [x] Handle hover events
  * ~~Handle keybindings~~ - Now a part of `LhasaReact`
  * [x] Handle scroll events
  * [x] FIX: WebAssembly OOM
  * [x] FIX: cxa_throw exceptions not caught
  * ~~Extend: `g_log` replacement should respect JS log verbosity settings~~ - Deferred to a separate issue

**Comment by hgonomeg** [comment]
Moved to `LhasaReact`:

* Handle keybindings
* (Re)implement text measurement
* Implement rendering of paths and arcs


Needs separate issue:
* `g_log` replacement extension - make it respect JS log verbosity settings
* Decide what to do with `gtk_widget_queue_resize` for the web + rework canvas sizing

**Comment by hgonomeg** [comment]
Before this can be merged, I need to add copyrights where appriopriate
