### ISSUE TITLE
Lhasa: Properly implement rendering of paths and arcs

### ISSUE THREAD

**Issue by hgonomeg** [hgonomeg/coot#68]
## Tasks 
* [x] Paths
  * [x] Figure out how cairo wraps those
  * [x] Replicate the same thing
  * [x] Redesign paths - current design is broken (impossible to make fills work in the frontend)
    * [x] Come up with a new design
    * [x] Implement it
    * [x] Reimplement cairo calls
* [x] Arcs - _do I need to change anything in C++?_ - **Yes, styling support. Part of _Paths_.**

**Comment by hgonomeg** [comment]
We'll need a major rewrite in another branch

**Comment by hgonomeg** [comment]
All nicely done.
